---
- name: install packages
  with_items: "{{ saslauthd_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart saslauthd

- name: configure saslauthd
  template:
    src: saslauthd.conf.j2
    dest: /usr/local/etc/saslauthd.conf
  notify:
    - restart saslauthd

- name: enable saslauthd
  template:
    src: saslauthd.j2
    dest: /etc/rc.conf.d/saslauthd
  notify:
    - restart saslauthd
